### ISSUE TITLE
Simplify RestorePlayerWaypoint with new APIs

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibGPS#2]
Use `SetPlayerWaypointByWorldLocation` to reset the original player waypoint without switching maps. Before starting to measure, we need to figure out the waypoint coordinates in the world space with the help of `GetUnitWorldPosition`, `GetMapPlayerPosition` and `GetMapPlayerWaypoint`.

**Comment by votan73** [comment]
https://github.com/sirinsidiator/ESO-LibGPS/pull/8
