### ISSUE TITLE
Add new measurements for world space

### ISSUE THREAD

**Issue by sirinsidiator** [sirinsidiator/ESO-LibGPS#3]
Add a separate set of scale and offset for the world coordinate space. This should be useful for addons using 3d features and also in order to calculate distances in meters.

**Comment by votan73** [comment]
I did that already. This should indeed be done after https://github.com/sirinsidiator/ESO-LibGPS/issues/2.
Restoring the waypoint is unnecessary complicate otherwise.
The pain is to keep the ping sound muted.

**Comment by votan73** [comment]
Maybe one should work the other way round: Intercepting the PingMap function and identify pings done by user.

**Comment by votan73** [comment]
```
-- p=player
-- w=waypoint
-- n=normalized
-- w=world

local _, pwx, _, pwy = GetUnitWorldPosition("player")
local pnx, pny = GetMapPlayerPosition("player")

local wwx, wwy = 2000000, 2000000
SetPlayerWaypointByWorldLocation(wwx, 1, wwy)
local wnx, wny = GetMapPlayerWaypoint()

local dwx, dwy = wwx-pwx, wwy-pwy
local dnx, dny = wnx-pnx, wny-pny
local scale = math.sqrt((dwx*dwx+dwy*dwy)/(dnx*dnx+dny*dny))
d("---", scale, math.sqrt((dwx*dwx)/(dnx*dnx)))
-- as the normalized width/height is 1, scale is also width/height in world-units

local wx2, wy2 = 0.15, 0.85
SetPlayerWaypointByWorldLocation((wx2-pnx)*scale+pwx, 1, (wy2-pny)*scale+pwy)
```

**Comment by votan73** [comment]
`
local function SetMeasurementWaypoint(x, y)
    -- this waypoint stays invisible for others
    lib.suppressCount = lib.suppressCount + 1
    LMP:SuppressPing(MAP_PIN_TYPE_PLAYER_WAYPOINT)
    SetPlayerWaypointByWorldLocation(x, 1, y)
    --LMP:SetMapPing(MAP_PIN_TYPE_PLAYER_WAYPOINT, MAP_TYPE_LOCATION_CENTERED, x, y)
end

local function getWorldUnits(dwx, dwy, dnx, dny)
    return zo_round(math.sqrt((dwx*dwx+dwy*dwy)/(dnx*dnx+dny*dny)))
end

local function CalculateMeasurements(mapId, localX, localY)
    local wwx, wwy = 2000000, 2000000
    SetMeasurementWaypoint(wwx, wwy)

    local _, pwx, _, pwy = GetUnitWorldPosition("player")
    local wpX, wpY = GetPlayerWaypoint()

    local dwx, dwy = wwx-pwx, wwy-pwy
    local dnx, dny = wpX-localX, wpY-localY

    -- add local points to seen maps
    local measurementPositions = {}
    table.insert(measurementPositions, { mapId = mapId, pX = localX, pY = localY, wpX = wpX, wpY = wpY, worldUnits = getWorldUnits(dwx, dwy, dnx, dny) })

    -- switch to zone map in order to get the mapIndex for the current location
    local x1, y1, x2, y2
    while not(GetMapType() == MAPTYPE_ZONE and GetMapContentType() ~= MAP_CONTENT_DUNGEON) do
        if (MapZoomOut() ~= SET_MAP_RESULT_MAP_CHANGED) then break end
        -- collect measurements for all maps we come through on our way to the zone map
        x1, y1, x2, y2 = GetReferencePoints()
        dnx, dny = x2-x1, y2-y1
        table.insert(measurementPositions, { mapId = GetMapTileTexture(), pX = x1, pY = y1, wpX = x2, wpY = y2, worldUnits = getWorldUnits(dwx, dwy, dnx, dny) })
    end
`

**Comment by sirinsidiator** [comment]
Will have to take a closer look at your code later.

Not sure intercepting the pings at set time would really make anything easier, since they are usually not passed as world coordinates, so converting them would still be necessary. Maybe we should try to get ZOS to add a new function GetMapPlayerWaypointWorldPosition? Another idea could be a separate new type of map ping which addons can use, which never shows up or makes a sound. That way it would all become quite simple.

As for measuring world coords, there are a few differences to measuring maps:
* We can set the waypoint to any coordinate except 0/0
* The origin for a world is always far outside the bounds of the local map (or at least I haven't seen anything to the contrary yet)
* A map can have n worlds and a world can have m maps. There is no direct relationship.
* We can only measure the world we are currently in (since the coordinate system is different for every zoneId)

The first two points mean we could utilize it to simplify measuring maps by setting the waypoint to world coords 1/1/1, since that should always work regardless. It just means we have to calculate the map offset afterwards.

Third one requires us to store world measurements independently of maps, since there could be maps with multiple worlds (like the Tamriel map). The main question here is how we would know which world measurements we should use in a case there are multiple available on a map with overlapping bounds.

The last one implies we have to improve how our api notifies about failures, e.g. when an addon tries to get a world position in a zone that has not been measured yet. This could for example happen when trying to display a distance in meters on a map with a world the player hasn't visited yet.
